registers:
- name: bypass
  description: With 0 the PLL is on while with 1 it is bypassed with ClkInRefPLL
  address: 0
  size: 1
  default: 0b1
  value: 0b0
- name: reset
  description: With 0 the PLL is Reset while with 1 it is running
  address: 1
  size: 1
  default: 0b0
  value: 0b1
- name: selectVctl
  description: Selects the Vcntrl for the martix VCOs from DAC (0) or PLL (1)
  address: 2
  size: 1
  default: 0b1
  value: 0b1
- name: dualedge
  description: Selects if the clock generator logic is single egde (0) or dual egde (1)
  address: 3
  size: 1
  default: 0b1
  value: 0b1
- name: clkphasediv
  description: Devides the clok phase frequency by 16 (00), 8 (01), 4 (10) or 2 (11)
  address: 4
  size: 2
  default: 0b01
  value: 0b01
- name: clkphasenum
  description: Configures the number of clock phases for the pixel column to 1 (000), 2 (001), 4 (010), 8 (011) or 16 (100)
  address: 6
  size: 3
  default: 0b000
  value: 0b000
- name: PLLOutConfig
  description: Selects the output of the PLLOut Pad
  address: 9
  size: 5
  default: 0b00000
  value: 0b00000
